version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
    - image: circleci/node:14
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - run: npm install
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
